### ISSUE TITLE
The "Usage" clause in the .md file has a line which belongs to another repo

### ISSUE THREAD

**Issue by Norod** [samdmarshall/plist-processor#1]
**Type of issue**: Minor Documentation Copy/Paste Error

---

**Related Files**: The .md file

---

**Description**: Under "Usage" it says "To use pyconfig to generate an .xcconfig file, you will have to pass it a path as input:" which was probably carried by a copy/paste from another repository

---

**Comment by samdmarshall** [comment]
Fixed, thanks for pointing this out.
